#ifndef UI_INC_MEASUREMENTBARLAYOUTCONFIG_H_
#define UI_INC_MEASUREMENTBARLAYOUTCONFIG_H_

#include "LayoutConfig.h"
#include "MainScrenBackgroundConfig.h"

//----------------------------------------------------------------------------------------------------//
#define VOLTAGE_MAX_TEXT_MARGIN_LEFT							8
#define VOLTAGE_MAX_TEXT_WIDGET_WIDTH							80
#define VOLTAGE_MAX_TEXT_WIDGET_HEIGHT							MAIN_SCREEN_MEASUREMENT_BAR_LAYOUT_HEIGHT
#define VOLTAGE_MAX_TEXT_WIDGET_X								(MAIN_SCREEN_MEASUREMENT_BAR_LAYOUT_X + VOLTAGE_MAX_TEXT_MARGIN_LEFT)
#define VOLTAGE_MAX_TEXT_WIDGET_Y								MAIN_SCREEN_MEASUREMENT_BAR_LAYOUT_Y
#define VOLTAGE_MAX_TEXT_WIDGET_BACKGROUND_COLOR				MAIN_SCREEN_BACKGROUND_COLOR
#define VOLTAGE_MAX_TEXT_WIDGET_ALIGNMENT						GRAPHICS_ALIGNMENT_MIDDLE_LEFT
#define VOLTAGE_MAX_TEXT_WIDGET_OUTLINE_WIDTH					0
#define VOLTAGE_MAX_TEXT_WIDGET_OUTLINE_COLOR					{{0x00, 0x00, 0x00}}
#define VOLTAGE_MAX_TEXT_WIDGET_FONT_SIZE						1
#define VOLTAGE_MAX_TEXT_WIDGET_FONT_COLOR						{{0xB4, 0xB4, 0xB4}}
//---------------------------------------------------------------------/
#define VOLTAGE_MIN_TEXT_WIDGET_WIDTH							80
#define VOLTAGE_MIN_TEXT_WIDGET_HEIGHT							MAIN_SCREEN_MEASUREMENT_BAR_LAYOUT_HEIGHT
#define VOLTAGE_MIN_TEXT_WIDGET_X								CACULATOR_POS_X(VOLTAGE_MAX_TEXT_WIDGET_WIDTH, VOLTAGE_MAX_TEXT_WIDGET_X)
#define VOLTAGE_MIN_TEXT_WIDGET_Y								MAIN_SCREEN_MEASUREMENT_BAR_LAYOUT_Y
#define VOLTAGE_MIN_TEXT_WIDGET_BACKGROUND_COLOR				MAIN_SCREEN_BACKGROUND_COLOR
#define VOLTAGE_MIN_TEXT_WIDGET_ALIGNMENT						GRAPHICS_ALIGNMENT_MIDDLE_LEFT
#define VOLTAGE_MIN_TEXT_WIDGET_OUTLINE_WIDTH					0
#define VOLTAGE_MIN_TEXT_WIDGET_OUTLINE_COLOR					{{0x00, 0x00, 0x00}}
#define VOLTAGE_MIN_TEXT_WIDGET_FONT_SIZE						1
#define VOLTAGE_MIN_TEXT_WIDGET_FONT_COLOR						{{0xB4, 0xB4, 0xB4}}

//----------------------------------------------------------------------------------------------------//
#endif /* UI_INC_MEASUREMENTBARLAYOUTCONFIG_H_ */
