#ifndef UI_INC_STATUSBARLAYOUTCONFIG_H_
#define UI_INC_STATUSBARLAYOUTCONFIG_H_

#include "LayoutConfig.h"
#include "MainScrenBackgroundConfig.h"
//-------------------------------------------------------------------------------------------------------------------------//
#define CACULATOR_POS_X(widgetWidthSize, widgetPosX)					(widgetWidthSize + widgetPosX)

#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_WIDTH							90
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_HEIGHT							MAIN_SCREEN_STATUS_BAR_LAYOUT_HEIGHT
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_X								0
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_Y								0
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_BACKGROUND_COLOR				MAIN_SCREEN_BACKGROUND_COLOR
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_ALIGNMENT						GRAPHICS_ALIGNMENT_MIDDLE_LEFT
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_OUTLINE_WIDTH					0
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_OUTLINE_COLOR					{{0x00, 0x00, 0x00}}
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_FONT_SIZE						1
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_FONT_COLOR						{{0xB4, 0xB4, 0xB4}}
//------------------------------------------------------------------------------------------------//
#define TIME_PER_DIVISION_TEXT_WIDGET_WIDTH								90
#define TIME_PER_DIVISION_TEXT_WIDGET_HEIGHT							MAIN_SCREEN_STATUS_BAR_LAYOUT_HEIGHT
#define TIME_PER_DIVISION_TEXT_WIDGET_X									CACULATOR_POS_X(VOLTAGE_PER_DIVISION_TEXT_WIDGET_WIDTH, VOLTAGE_PER_DIVISION_TEXT_WIDGET_X)
#define TIME_PER_DIVISION_TEXT_WIDGET_Y									0
#define TIME_PER_DIVISION_TEXT_WIDGET_BACKGROUND_COLOR					MAIN_SCREEN_BACKGROUND_COLOR
#define TIME_PER_DIVISION_TEXT_WIDGET_ALIGNMENT							GRAPHICS_ALIGNMENT_MIDDLE_LEFT
#define TIME_PER_DIVISION_TEXT_WIDGET_OUTLINE_WIDTH						0
#define TIME_PER_DIVISION_TEXT_WIDGET_OUTLINE_COLOR						{{0x00, 0x00, 0x00}}
#define TIME_PER_DIVISION_TEXT_WIDGET_FONT_SIZE							1
#define TIME_PER_DIVISION_TEXT_WIDGET_FONT_COLOR						{{0xB4, 0xB4, 0xB4}}
//------------------------------------------------------------------------------------------------//
#define ACQUISITTION_STATUS_TEXT_WIDGET_WIDTH							30
#define ACQUISITTION_STATUS_TEXT_WIDGET_HEIGHT							MAIN_SCREEN_STATUS_BAR_LAYOUT_HEIGHT
#define ACQUISITTION_STATUS_TEXT_WIDGET_X								CACULATOR_POS_X(TIME_PER_DIVISION_TEXT_WIDGET_WIDTH, TIME_PER_DIVISION_TEXT_WIDGET_X)
#define ACQUISITTION_STATUS_TEXT_WIDGET_Y								0
#define ACQUISITTION_STATUS_TEXT_WIDGET_BACKGROUND_COLOR				MAIN_SCREEN_BACKGROUND_COLOR
#define ACQUISITTION_STATUS_TEXT_WIDGET_ALIGNMENT						GRAPHICS_ALIGNMENT_MIDDLE_LEFT
#define ACQUISITTION_STATUS_TEXT_WIDGET_OUTLINE_WIDTH					0
#define ACQUISITTION_STATUS_TEXT_WIDGET_OUTLINE_COLOR					{{0x00, 0x00, 0x00}}
#define ACQUISITTION_STATUS_TEXT_WIDGET_FONT_SIZE						1
#define ACQUISITTION_STATUS_TEXT_WIDGET_FONT_COLOR						{{0xB4, 0xB4, 0xB4}}
//------------------------------------------------------------------------------------------------//
#define ZOOM_MODE_TEXT_WIDGET_WIDTH										70
#define ZOOM_MODE_TEXT_WIDGET_HEIGHT									MAIN_SCREEN_STATUS_BAR_LAYOUT_HEIGHT
#define ZOOM_MODE_TEXT_WIDGET_X											CACULATOR_POS_X(ACQUISITTION_STATUS_TEXT_WIDGET_WIDTH, ACQUISITTION_STATUS_TEXT_WIDGET_X)
#define ZOOM_MODE_TEXT_WIDGET_Y											0
#define ZOOM_MODE_TEXT_WIDGET_BACKGROUND_COLOR							MAIN_SCREEN_BACKGROUND_COLOR
#define ZOOM_MODE_TEXT_WIDGET_ALIGNMENT									GRAPHICS_ALIGNMENT_MIDDLE_LEFT
#define ZOOM_MODE_TEXT_WIDGET_OUTLINE_WIDTH								0
#define ZOOM_MODE_TEXT_WIDGET_OUTLINE_COLOR								{{0x00, 0x00, 0x00}}
#define ZOOM_MODE_TEXT_WIDGET_FONT_SIZE									1
#define ZOOM_MODE_TEXT_WIDGET_FONT_COLOR								{{0xB4, 0xB4, 0xB4}}
//------------------------------------------------------------------------------------------------------------------------//

#endif /* UI_INC_STATUSBARLAYOUTCONFIG_H_ */
