#ifndef UI_INC_STATUSBARLAYOUTCONFIG_H_
#define UI_INC_STATUSBARLAYOUTCONFIG_H_

#include "LayoutConfig.h"
#include "MainScrenBackgroundConfig.h"
//-------------------------------------------------------------------------------------------------------------------------//
#define VOLTAGE_PER_DIVISION_TEXT_MARGIN_LEFT							8
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_WIDTH							60
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_HEIGHT							MAIN_SCREEN_STATUS_BAR_LAYOUT_HEIGHT
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_X								(MAIN_SCREEN_STATUS_BAR_LAYOUT_X + VOLTAGE_PER_DIVISION_TEXT_MARGIN_LEFT)
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_Y								MAIN_SCREEN_STATUS_BAR_LAYOUT_Y
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_BACKGROUND_COLOR				MAIN_SCREEN_BACKGROUND_COLOR
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_ALIGNMENT						GRAPHICS_ALIGNMENT_MIDDLE_LEFT
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_OUTLINE_WIDTH					0
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_OUTLINE_COLOR					{{0x00, 0x00, 0x00}}
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_FONT_SIZE						1
#define VOLTAGE_PER_DIVISION_TEXT_WIDGET_FONT_COLOR						{{0xB4, 0xB4, 0xB4}}
//------------------------------------------------------------------------------------------------//
#define TIME_PER_DIVISION_TEXT_WIDGET_WIDTH								60
#define TIME_PER_DIVISION_TEXT_WIDGET_HEIGHT							MAIN_SCREEN_STATUS_BAR_LAYOUT_HEIGHT
#define TIME_PER_DIVISION_TEXT_WIDGET_X									CACULATOR_POS_X(VOLTAGE_PER_DIVISION_TEXT_WIDGET_WIDTH, VOLTAGE_PER_DIVISION_TEXT_WIDGET_X)
#define TIME_PER_DIVISION_TEXT_WIDGET_Y									0
#define TIME_PER_DIVISION_TEXT_WIDGET_BACKGROUND_COLOR					MAIN_SCREEN_BACKGROUND_COLOR
#define TIME_PER_DIVISION_TEXT_WIDGET_ALIGNMENT							GRAPHICS_ALIGNMENT_MIDDLE_LEFT
#define TIME_PER_DIVISION_TEXT_WIDGET_OUTLINE_WIDTH						0
#define TIME_PER_DIVISION_TEXT_WIDGET_OUTLINE_COLOR						{{0x00, 0x00, 0x00}}
#define TIME_PER_DIVISION_TEXT_WIDGET_FONT_SIZE							1
#define TIME_PER_DIVISION_TEXT_WIDGET_FONT_COLOR						{{0xB4, 0xB4, 0xB4}}
//------------------------------------------------------------------------------------------------//
#define ACQUISITTION_STATUS_TEXT_WIDGET_WIDTH							24
#define ACQUISITTION_STATUS_TEXT_WIDGET_HEIGHT							MAIN_SCREEN_STATUS_BAR_LAYOUT_HEIGHT
#define ACQUISITTION_STATUS_TEXT_WIDGET_X								CACULATOR_POS_X(TIME_PER_DIVISION_TEXT_WIDGET_WIDTH, TIME_PER_DIVISION_TEXT_WIDGET_X)
#define ACQUISITTION_STATUS_TEXT_WIDGET_Y								0
#define ACQUISITTION_STATUS_TEXT_WIDGET_BACKGROUND_COLOR				MAIN_SCREEN_BACKGROUND_COLOR
#define ACQUISITTION_STATUS_TEXT_WIDGET_ALIGNMENT						GRAPHICS_ALIGNMENT_MIDDLE_LEFT
#define ACQUISITTION_STATUS_TEXT_WIDGET_OUTLINE_WIDTH					0
#define ACQUISITTION_STATUS_TEXT_WIDGET_OUTLINE_COLOR					{{0x00, 0x00, 0x00}}
#define ACQUISITTION_STATUS_TEXT_WIDGET_FONT_SIZE						1
#define ACQUISITTION_STATUS_TEXT_WIDGET_FONT_COLOR						{{0xB4, 0xB4, 0xB4}}
//------------------------------------------------------------------------------------------------//
#define ZOOM_SCALE_TEXT_WIDGET_WIDTH									30
#define ZOOM_SCALE_TEXT_WIDGET_HEIGHT									MAIN_SCREEN_STATUS_BAR_LAYOUT_HEIGHT
#define ZOOM_SCALE_TEXT_WIDGET_X										CACULATOR_POS_X(ACQUISITTION_STATUS_TEXT_WIDGET_WIDTH, ACQUISITTION_STATUS_TEXT_WIDGET_X)
#define ZOOM_SCALE_TEXT_WIDGET_Y										0
#define ZOOM_SCALE_TEXT_WIDGET_BACKGROUND_COLOR							MAIN_SCREEN_BACKGROUND_COLOR
#define ZOOM_SCALE_TEXT_WIDGET_ALIGNMENT								GRAPHICS_ALIGNMENT_MIDDLE_LEFT
#define ZOOM_SCALE_TEXT_WIDGET_OUTLINE_WIDTH							0
#define ZOOM_SCALE_TEXT_WIDGET_OUTLINE_COLOR							{{0x00, 0x00, 0x00}}
#define ZOOM_SCALE_TEXT_WIDGET_FONT_SIZE								1
#define ZOOM_SCALE_TEXT_WIDGET_FONT_COLOR								{{0xB4, 0xB4, 0xB4}}
//------------------------------------------------------------------------------------------------//
#define TRIGGER_MODE_TEXT_WIDGET_WIDTH									30
#define TRIGGER_MODE_TEXT_WIDGET_HEIGHT									MAIN_SCREEN_STATUS_BAR_LAYOUT_HEIGHT
#define TRIGGER_MODE_TEXT_WIDGET_X										CACULATOR_POS_X(ZOOM_SCALE_TEXT_WIDGET_WIDTH, ZOOM_SCALE_TEXT_WIDGET_X)
#define TRIGGER_MODE_TEXT_WIDGET_Y										0
#define TRIGGER_MODE_TEXT_WIDGET_BACKGROUND_COLOR						MAIN_SCREEN_BACKGROUND_COLOR
#define TRIGGER_MODE_TEXT_WIDGET_ALIGNMENT								GRAPHICS_ALIGNMENT_MIDDLE_LEFT
#define TRIGGER_MODE_TEXT_WIDGET_OUTLINE_WIDTH							0
#define TRIGGER_MODE_TEXT_WIDGET_OUTLINE_COLOR							{{0x00, 0x00, 0x00}}
#define TRIGGER_MODE_TEXT_WIDGET_FONT_SIZE								1
#define TRIGGER_MODE_TEXT_WIDGET_FONT_COLOR								{{0xB4, 0xB4, 0xB4}}
//------------------------------------------------------------------------------------------------//
#define TRIGGER_EDGE_TEXT_WIDGET_WIDTH									40
#define TRIGGER_EDGE_TEXT_WIDGET_HEIGHT									MAIN_SCREEN_STATUS_BAR_LAYOUT_HEIGHT
#define TRIGGER_EDGE_TEXT_WIDGET_X										CACULATOR_POS_X(TRIGGER_MODE_TEXT_WIDGET_WIDTH, TRIGGER_MODE_TEXT_WIDGET_X)
#define TRIGGER_EDGE_TEXT_WIDGET_Y										0
#define TRIGGER_EDGE_TEXT_WIDGET_BACKGROUND_COLOR						MAIN_SCREEN_BACKGROUND_COLOR
#define TRIGGER_EDGE_TEXT_WIDGET_ALIGNMENT								GRAPHICS_ALIGNMENT_MIDDLE_LEFT
#define TRIGGER_EDGE_TEXT_WIDGET_OUTLINE_WIDTH							0
#define TRIGGER_EDGE_TEXT_WIDGET_OUTLINE_COLOR							{{0x00, 0x00, 0x00}}
#define TRIGGER_EDGE_TEXT_WIDGET_FONT_SIZE								1
#define TRIGGER_EDGE_TEXT_WIDGET_FONT_COLOR								{{0xB4, 0xB4, 0xB4}}
//------------------------------------------------------------------------------------------------//
#define TRIGGER_LEVEL_TEXT_WIDGET_WIDTH									70
#define TRIGGER_LEVEL_TEXT_WIDGET_HEIGHT								MAIN_SCREEN_STATUS_BAR_LAYOUT_HEIGHT
#define TRIGGER_LEVEL_TEXT_WIDGET_X										CACULATOR_POS_X(TRIGGER_EDGE_TEXT_WIDGET_WIDTH, TRIGGER_EDGE_TEXT_WIDGET_X)
#define TRIGGER_LEVEL_TEXT_WIDGET_Y										0
#define TRIGGER_LEVEL_TEXT_WIDGET_BACKGROUND_COLOR						MAIN_SCREEN_BACKGROUND_COLOR
#define TRIGGER_LEVEL_TEXT_WIDGET_ALIGNMENT								GRAPHICS_ALIGNMENT_MIDDLE_LEFT
#define TRIGGER_LEVEL_TEXT_WIDGET_OUTLINE_WIDTH							0
#define TRIGGER_LEVEL_TEXT_WIDGET_OUTLINE_COLOR							{{0x00, 0x00, 0x00}}
#define TRIGGER_LEVEL_TEXT_WIDGET_FONT_SIZE								1
#define TRIGGER_LEVEL_TEXT_WIDGET_FONT_COLOR							{{0xB4, 0xB4, 0xB4}}
//------------------------------------------------------------------------------------------------------------------------//

#endif /* UI_INC_STATUSBARLAYOUTCONFIG_H_ */
