#ifndef UI_INC_WAVEFORMLAYOUTCONFIG_H_
#define UI_INC_WAVEFORMLAYOUTCONFIG_H_

#include <LayoutConfig.h>

//----------------------------------------------------------------------------------------------------//
#define WAVEFORM_X									(MAIN_SCREEN_WAVEFORM_LAYOUT_WIDTH - WAVEFORM_WIDTH) / 2
#define WAVEFORM_Y									MAIN_SCREEN_WAVEFORM_LAYOUT_Y
#define WAVEFORM_WIDTH								304
#define WAVEFORM_HEIGH								204

#define WAVEFORM_OUTLINE_WIDTH						2
#define WAVEFORM_OUTLINE_COLOR						{{0x80, 0x00, 0x00}}
#define WAVEFORM_CONTENT_WIDTH						(WAVEFORM_WIDTH - WAVEFORM_OUTLINE_WIDTH * 2)
#define WAVEFORM_CONTENT_HEIGHT						(WAVEFORM_HEIGH - WAVEFORM_OUTLINE_WIDTH * 2)

#define WAVEFORM_BACKGROUND							{{0x00, 0x00, 0x00}}
#define WAVEFORM_DEVISION_PIXEL						20
#define WAVEFORM_VETICAL_LINE_X(x)					(x * WAVEFORM_DEVISION_PIXEL + WAVEFORM_X)
#define WAVEFORM_VETICAL_LINE_Y						(WAVEFORM_Y + WAVEFORM_OUTLINE_WIDTH)
#define WAVEFORM_VETICAL_LINE_HEIGHT				WAVEFORM_CONTENT_HEIGHT
#define WAVEFORM_VETICAL_LINE_WIDTH					1
#define WAVEFORM_HORIZONTAL_LINE_X					(WAVEFORM_X + WAVEFORM_OUTLINE_WIDTH)
#define WAVEFORM_HORIZONTAL_LINE_Y(y)				(y * WAVEFORM_DEVISION_PIXEL + WAVEFORM_Y)
#define WAVEFORM_HORIZONTAL_LINE_WIDTH				WAVEFORM_CONTENT_WIDTH
#define WAVEFORM_HORIZONTAL_LINE_HEIGHT				1
#define WAVEFORM_LINE_SET							{{0x20, 0x20, 0x20}}

//----------------------------------------------------------------------------------------------------//


#endif /* UI_INC_WAVEFORMLAYOUTCONFIG_H_ */
